### ISSUE TITLE
Ask folder

### ISSUE THREAD

**Issue by ghost** [piroor/save-selected-tabs-to-files#1]
please add option to ever ask the folder, and to remember the last folder used

**Comment by piroor** [comment]
This looks impossible due to restrictions of the WebExtensions API.

* [`downloads.download()` doesn't provide ability to choose a folder.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download)
* There looks no way to choose a folder itself via regular HTML form controls.

**Comment by ghost** [comment]
all right, @piroor please if possible create some basic buttons for firefox we, like "Toggle Work Offline", "Toggle CSS per Tab", and "Open Largest Images of All Tabs"  Today have some plugins but don't work well.

thank you...

**Comment by piroor** [comment]
Did you commented about another feature request about a toolbar button added by this addon?

**Comment by ghost** [comment]
No!, is because I know you is an old extension developer, and before I used the "Toolbar Buttons" extension, but now, have a lot of basic buttons not available in WE,  like "Toggle Work Offline", "Toggle CSS per Tab", and "Open Largest Images of All Tabs" today have some plugins but don't work well. I just ask you to do some buttons if possible some day. Thanks

**Comment by ghost** [comment]
@piroor you said which you can't add an feature to ask folders, because the API ever save all in "default downloads folder", but you can then add an feature or option to ever ask the name of "subfolder"? This is possible, and can be very useful. Like: 

Downloads/Asked Folder 1
Downloads/Asked Folder 2
Downloads/Asked Folder 3

**Comment by piroor** [comment]
> No!, is because I know you is an old extension developer, and before I used the "Toolbar Buttons" extension, but now, have a lot of basic buttons not available in WE, like "Toggle Work Offline", "Toggle CSS per Tab", and "Open Largest Images of All Tabs" today have some plugins but don't work well. I just ask you to do some buttons if possible some day. Thanks

I'm sorry but still cannot understand what you actually meant. Which is the one you meant?:

* A) A toolbar button to start downloading of selected tabs, which is a new feature of this addon.
* B) Multiple customizable toolbar buttons provided by a single addon, which is not this addon but a new another addon.
* C) Others.

Anyway, I agree that an ability to ask the name of the subfolder for each new downlaod looks useful.

**Comment by piroor** [comment]
After the commit 65d9660 if you put a placeholder `%input%` to the prefix subfolder path, a dialog will appear in the tab.
