### ISSUE TITLE
Can multi-selected tabs save altogether as a group?

### ISSUE THREAD

**Issue by Coldblackice** [piroor/save-selected-tabs-to-files#3]
Currently, saving a multi-tab group calls a Windows Save-As dialog for each and every individual tab, one by one, one after the other. This pretty much negates the brunt of utility for an addon like this, since it's essentially just voiding the need to switch between tabs, functioning like a macro or AHK script.

Is it possible for the multi-selected tabs to be saved altogether at once without having to pop individual save-dialogs for each one?

Happening with Firefoxes v86 + v85, W10 Pro x64.

**Comment by piroor** [comment]
This addon is not designed to show the "Save as" common dialog, instead this downloads files under a folder silently. Even if you configure this to ask the folder name before saving, this just asks the name of the folder once for multiple highlighted tabs. Do you use other similar addon?

**Comment by Coldblackice** [comment]
> 
> 
> This addon is not designed to show the "Save as" common dialog, instead this downloads files under a folder silently. Even if you configure this to ask the folder name before saving, this just asks the name of the folder once for multiple highlighted tabs. Do you use other similar addon?

Ah, good to know that's how it's meant to work. I guess that means there must be something on my end causing the issue. I can't think of any other addons I have that do similar functions (which might be interfering), aside from the Tree Style addon modules, which I assume aren't the cause. 

Is there a way for me to access a debug-mode/interface to catch what's happening when I trigger the "Save Tabs as Files" command? The issue must be either an addon I have or a browser config setting I've changed.

I'm hoping there's a way I can debug the behind-the-scenes calls so I can step/trace through the execution flow, rather than having to do it the "old school" way of just disabling everything + creating a new profile, then gradually sifting things back in until the issue happens again. 

It'd be preferable to attack this from the front, if possible!

**Comment by piroor** [comment]
I think that you should do a bisection for such cases.

1. Disable all other addons except "Save Selected Tabs to Files".
2. Try to reproduce the problem.
   * If you don't see any problem, it looks a problem from a combination of addons, so it is the time to do bisection of addons.
      1. Activate half of rest addons.
      2. Try to reproduce the problem. If the problem happens, activated addons are dirty, otherwise deactivated addons are dirty.
      3. Activate only SSTF and dirty addons.
      4. Repeat steps 2 and 3 until there is only one dirty addon is left.
      5. Start inspection of the last dirty addon with the debugger started via `about:debugging`.
    * If you still see the problem, the cause may be Firefox itself, any userChrome.js script, or any security software (like
Windows Defender). You'll start debugging of Firefox itself with these steps:
      1. Activate the Browser Toolbox. https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox
      2. Open the Browser Toolbox.
      3. Find the file about tab downloading.
      4. Set a breakpoint around the code.

**Comment by piroor** [comment]
https://searchfox.org/ will help you to find out where the code about downloading exists in.

**Comment by irvnriir** [comment]
This happens when "Always ask you where to save files" `FIrefox \ Options` setting is on .

**Comment by piroor** [comment]
@irvnriir Thanks! I've confirmed that the problem described here reproduces with the option. Something notes about the option looks required on the initial startup.

**Comment by piroor** [comment]
I've added a notification message about Firefox's "Always ask you where to save files".
