### ISSUE TITLE
Filename TOO LONG?

### ISSUE THREAD

**Issue by BlackholeForever** [piroor/save-selected-tabs-to-files#5]
## Short description
Extension generates a filename based on the TITLE of the page... I think if it's TOO LONG (or if there is an invalid character?), it cannot download the tab to file due to filesystem filename constraints (Windows 7). At least... it seems to be affected by pages having LONG titles.

Also, can we have an option to generate the filename, simply based on the URL (e.g., www.amazon.com-dp-B00NR2VMNC)?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Try this page: https://www.amazon.com/dp/B00NR2VMNC

For the above given URL, a 0-byte file is created in c:\Users\Admin\Downloads\Saved Tabs:
Amazon.com_ TP-Link AC750 Wifi Range Extender _ Up to 750Mbps _ Dual Band WiFi Extender, Repeater, Wifi Signal Booster, Access Point_ Easy Set-Up _ Extends Wifi to Smart Home & Alexa Devices (RE200)_ Computers & Accessories

When I download it manually (correctly downloaded), this the filename that Firefox writes to (c:\Users\Admin\Downloads\Saved Tabs):
Amazon.com TP-Link AC750 Wifi Range Extender Up to 750Mbps Dual Band WiFi Extender, Repeater, Wifi Signal Booster, Access Point Easy Set-Up Extends Wifi to Smart Home & Alexa Devices (RE200) Computers & Accessories.htm

## Expected result
Downloaded file.

## Actual result
0-byte (EMPTY) file.

## Environment

 * Platform (OS):  Windows 7 (64-bit)
 * Version of Firefox:  90.0.2 (64-bit)
 * Version (or revision) of Multiple Tab Handler:  Version 1.1.5

**Comment by piroor** [comment]
Thanks, I've introduced an option to set the max length of file name and released a new version 1.1.6.
