### ISSUE TITLE
downloads fail if too many tabs

### ISSUE THREAD

**Issue by ChameleonScales** [piroor/save-selected-tabs-to-files#8]
## Short description
If firefox is set up to autosave (not prompt for directory) and too many tabs are selected, a large part of them fail to download.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install Save Selected Tabs to Files
 4.  Uncheck "Always ask you where to save files" in Firefox's preferences
 5. open a large number of tabs (90 in my case)
 6. Select them all
 7. Right click > Save tabs as files : some will fail to download

## Environment

 * Platform (OS): Debian 11
 * Version of Firefox: 103.0
 * Version (or revision) of Multiple Tab Handler: 1.1.6

**Comment by piroor** [comment]
OK, I've introduced changes to run only 10 downloads at a time.
